stages:
  - nodebuild
  - test
  - nginxbuild

include:
  remote: https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/.gitlab-ci-before_script.yml

variables:
  V_NUM: '0.0.1' # TODO probably a way to get this from package.json instead
  REGISTRY: 'code.ornl.gov:4567/rse/datastreams/ssm/frontend/search-upload-ui'
  NODE_URL: '${REGISTRY}/node'
  NGINX_URL: '${REGISTRY}/nginx'
  NODE_IMAGE_NAME: 'datastreams-fe-node'
  DOCKER_APP_WORKDIR: '/usr/local/src'

after_script:
  - func_rse_docker_cleanup
  - sudo chown -R gitlab-runner .

nodebuild:
  stage: nodebuild
  script:
    - func_rse_docker_cleanup
    - docker build -f Dockerfile.node --build-arg ci=true -t $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM
  tags:
    - rse-nds-builder

# fail if auditing returns 'high' or 'critical' vulnerabilities, report all vulnerabilities
test_audit:
  stage: test
  variables:
    AUDIT_OUTFILE: 'audit-report.txt'
  artifacts:
    when: always
    paths:
      - audit-report.txt
  script:
    - func_rse_docker_cleanup
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM
    - docker run --name $NODE_IMAGE_NAME $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM sh -c "bin/audit.js -l high" > $AUDIT_OUTFILE
  tags:
    - rse-nds-builder

test_lint:
  stage: test
  script:
    - func_rse_docker_cleanup
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM
    - docker run --name $NODE_IMAGE_NAME $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM sh -c "yarn run assert-no-warnings"
  tags:
    - rse-nds-builder

test_jest:
  stage: test
  script:
    - func_rse_docker_cleanup
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM
    - docker run --name $NODE_IMAGE_NAME $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM sh -c "yarn test"
  tags:
    - rse-nds-builder

.nginxbuild:
  script:
    - func_rse_docker_cleanup
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM
    - docker run --name $NODE_IMAGE_NAME $NODE_URL/$CI_COMMIT_REF_NAME:$V_NUM sh -c "yarn run build"
    - sudo rm -rf .ci/build || true
    - docker cp $NODE_IMAGE_NAME:$DOCKER_APP_WORKDIR/build .ci/build
    - docker build -f .ci/Dockerfile.nginx --build-arg DEFAULT_NGINX_CONF=$DEFAULT_NGINX_CONF -t $NGINX_URL/$CI_COMMIT_REF_NAME:$V_NUM .ci/
    - docker push $NGINX_URL/$CI_COMMIT_REF_NAME:$V_NUM

nginxbuild-nossl:
  stage: nginxbuild
  extends: .nginxbuild
  variables:
    DEFAULT_NGINX_CONF: 'default-nossl.conf'
  only:
    - dev
  tags:
    - rse-nds-builder

nginxbuild-ssl:
  stage: nginxbuild
  extends: .nginxbuild
  variables:
    DEFAULT_NGINX_CONF: 'default-ssl.conf'
  only:
    - qa
    - master
  tags:
    - rse-nds-builder
