stages:
    - carbonbuild
    - yarninstall
    - yarntest
    - frontendbuild

variables:
    V_NUM: "v0.0.1"
    CONTAINER_URL: "code.ornl.gov:4567/rse/datastreams/nuclear-datastreams/frontend"    
    
carbonbuild:
    stage: carbonbuild
    before_script:
        - sudo systemctl stop docker
        - sudo rm -rf /var/lib/docker
        - sudo systemctl start docker
        - sudo docker rmi -f $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM
    script:
        - docker build -f Dockerfile-carbon -t $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM .
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM
    tags:
        - rse-nds-builder

yarninstall:
    stage: yarninstall
    artifacts:
        untracked: true
    script:
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CACONTAINER_URLRBON_URL/$CI_COMMIT_REF_NAME:$V_NUM
        - docker run -v $PWD:/app $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM bash -c "cd data-ingestion-ui && yarn install"
    tags:
        - rse-nds-builder

yarntest:
    stage: yarntest
    dependencies: 
        - yarninstall
    script:
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM
        - docker run -v $PWD:/app $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM bash -c "cd data-ingestion-ui && yarn test-ci"
    tags:
        - rse-nds-builder

frontendbuild:
    stage: frontendbuild
    dependencies: 
        - yarninstall
    before_script:
        - sudo systemctl stop docker
        - sudo rm -rf /var/lib/docker
        - sudo systemctl start docker
        - sudo docker rmi -f $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM
    script:
        - docker build -f Dockerfile-frontend -t $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM .
        - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CONTAINER_URL/$CI_COMMIT_REF_NAME:$V_NUM
    tags:
        - rse-nds-builder

