# This file is only for local developers, and should really only be used if you don't want to install node/yarn on your machine

services:
  app:
    build:
      context: .
    image: ssm-fe-node # don't push this image, for local caching only
    container_name: ssm-fe-node
    restart: unless-stopped
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_API_URL: 'http://localhost:8080/catalog/api'
      REACT_APP_FILE_CONVERTER_URL: 'http://localhost:8080/file-converter'
      REACT_APP_ML_NOTEBOOKS_URL: 'http://localhost:8080/notebooks'
      REACT_APP_ML_UI_URL: 'http://localhost:8082/machine-learning'

    ports:
      # main application port
      # note that if you are using Docker, do not set PORT in any env file.
      - '3000:3000'
      # websocket port
      #- '35729:35729'
    # this is needed so `yarn start` can open the browser
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/local/src
      - /usr/local/src/node_modules
      - /usr/local/src/build
