name: Code checks

on:
  push:
    branches:
      - '*'

jobs:
  code-checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container image
        run: docker build -f deployment-ctx/Dockerfile -t ssm-fe-nginx deployment-ctx/

  publish-container-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [code-checks]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ui ml image
        uses: docker/build-push-action@v4
        with:
          context: deployment-ctx/
          file: deployment-ctx/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/smart-spectral-matching/ssm-ui-catalog:${{ github.ref_name }}-${{github.sha}}
