name: Code checks

on:
  push:
    branches:
      - '*'

jobs:
  code-checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build development container image
        run: docker build  -t ssm-fe-node .

      - name: Run build in a development container
        run: docker run --name ssm-fe-node-build ssm-fe-node sh -c "echo '' > .env && yarn run build"

      - name: Copy build out of development container onto host
        run: docker cp ssm-fe-node-build:/usr/local/src/build deployment-ctx/build

      - name: Build production container image using build artifact from previous step
        run: docker build -f deployment-ctx/Dockerfile -t ssm-fe-nginx deployment-ctx/

      - name: Upload build as artifact for publish job
        uses: actions/upload-artifact@v4
        with:
          name: 'yarn-build'
          path: deployment-ctx/build

  publish-container-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [code-checks]
    steps:
      - name: Download build as artifact from previous build job
        uses: actions/download-artifact@v4
        with:
          name: 'yarn-build'
          path: deployment-ctx/build

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ui ml image
        uses: docker/build-push-action@v4
        with:
          context: deployment-ctx/
          file: deployment-ctx/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/smart-spectral-matching/ssm-ui-catalog:${{ github.ref_name }}-${{github.sha}}
